# Generated by Django 3.1.7 on 2021-04-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210403_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='isApply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='isVoting',
            field=models.BooleanField(default=False),
        ),
    ]
