# Generated by Django 3.1.7 on 2021-04-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210404_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='whyApply',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
