# Generated by Django 3.1.7 on 2021-04-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_candidate_whyapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='isCandidate',
            field=models.BooleanField(default=False),
        ),
    ]
