# Generated by Django 3.1.7 on 2021-04-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_candidate_iscandidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='isCandidate',
        ),
    ]
