# Generated by Django 3.1.7 on 2021-04-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_candidate_iscandidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
