# Generated by Django 3.1.7 on 2021-04-06 07:13

from django.db import migrations
import django.utils.timezone
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20210406_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='image',
            field=django_fields.fields.DefaultStaticImageField(blank=True, default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
