# Generated by Django 3.1.7 on 2021-04-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20210406_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cast_parcentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
