# Generated by Django 3.1.7 on 2021-04-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_candidate_cast_parcentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='applyingFor',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
