# Generated by Django 3.1.7 on 2021-04-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_customeruser_applyingfor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='isVoting',
        ),
        migrations.AddField(
            model_name='post',
            name='isVoting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_image',
            field=models.ImageField(default='profile.png', upload_to='profile_pic'),
        ),
    ]
