# Generated by Django 3.1.7 on 2021-04-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_vote_candidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='name_candidate',
            new_name='candidate_title',
        ),
    ]
