# Generated by Django 3.1.7 on 2021-04-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20210407_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='candidate_title',
            new_name='name_candidate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='isVoting',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.AddField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.candidate'),
        ),
    ]
