# Generated by Django 3.1.7 on 2021-04-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20210407_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isVoting',
            field=models.BooleanField(default=False),
        ),
    ]
