# Generated by Django 3.1.7 on 2021-04-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_post_isvoting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='applyingFor',
        ),
        migrations.AddField(
            model_name='candidate',
            name='applyingFor',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
