# Generated by Django 3.1.7 on 2021-04-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20210407_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='image',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
