# Generated by Django 3.1.7 on 2021-04-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_vote_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
    ]
