# Generated by Django 3.1.7 on 2021-04-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_vote_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
