# Generated by Django 3.1.7 on 2021-04-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20210413_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='voted',
        ),
    ]
