export const CANDIDATES_LIST_REQUEST = 'CANDIDATES_LIST_REQUEST';
export const CANDIDATES_LIST_SUCCESS = 'CANDIDATES_LIST_SUCCESS';
export const CANDIDATES_LIST_FAIL = 'CANDIDATES_LIST_FAIL';
export const CANDIDATES_LIST_RESET = 'CANDIDATES_LIST_RESET';

export const APPLY_CREATE_REQUEST = 'APPLY_CREATE_REQUEST';
export const APPLY_CREATE_SUCCESS = 'APPLY_CREATE_SUCCESS';
export const APPLY_CREATE_FAIL = 'APPLY_CREATE_FAIL';
export const APPLY_CREATE_RESET = 'APPLY_CREATE_RESET';

export const CANDIDATE_DETAILS_REQUEST = 'CANDIDATE_DETAILS_REQUEST';
export const CANDIDATE_DETAILS_SUCCESS = 'CANDIDATE_DETAILS_SUCCESS';
export const CANDIDATE_DETAILS_FAIL = 'CANDIDATE_DETAILS_FAIL';
export const CANDIDATE_DETAILS_RESET = 'CANDIDATE_DETAILS_RESET';

export const CANDIDATE_UPDATE_REQUEST = 'CANDIDATE_UPDATE_REQUEST';
export const CANDIDATE_UPDATE_SUCCESS = 'CANDIDATE_UPDATE_SUCCESS';
export const CANDIDATE_UPDATE_FAIL = 'CANDIDATE_UPDATE_FAIL';
export const CANDIDATE_UPDATE_RESET = 'CANDIDATE_UPDATE_RESET';

export const CANDIDATE_DELETE_REQUEST = 'CANDIDATE_DELETE_REQUEST';
export const CANDIDATE_DELETE_SUCCESS = 'CANDIDATE_DELETE_SUCCESS';
export const CANDIDATE_DELETE_FAIL = 'CANDIDATE_DELETE_FAIL';

export const CANDIDATE_POST_REQUEST = 'CANDIDATE_POST_REQUEST';
export const CANDIDATE_POST_SUCCESS = 'CANDIDATE_POST_SUCCESS';
export const CANDIDATE_POST_FAIL = 'CANDIDATE_POST_FAIL';
export const CANDIDATE_POST_RESET = 'CANDIDATE_POST_RESET';
